wandb_version: 1

architecture:
  desc: null
  value: EfficientNet-B0
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 251
learning_rate:
  desc: null
  value: 0.0003
weight_decay:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684139743.527461
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.2
      8:
      - 3
      - 5
