wandb_version: 1

batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0003
min_lr:
  desc: null
  value: 1.0e-06
weight_decay:
  desc: null
  value: 0.0001
split_num:
  desc: null
  value: 900
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683895679.291741
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 63
      3:
      - 3
      - 15
      - 16
      - 23
      4: 3.7.16
      5: 0.15.2
      8:
      - 3
      - 5
